create or replace TABLE MATRIX.PUBLIC.ADRESSE (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 order,
	ID_USER NUMBER(38,0),
	ADRESSE VARCHAR(100),
	CITY VARCHAR(50),
	CODEPOSTAL VARCHAR(20),
	COUNTRY VARCHAR(50),
	primary key (ID)
);



create or replace TABLE MATRIX.PUBLIC.ARTICLE_SCIENTIFIQUE (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 order,
	NOCONTRIBUTION VARCHAR(100),
	TITRECONTRIBUTION VARCHAR(100),
	INSTITUTION VARCHAR(100),
	TRRACKPREFERENCE VARCHAR(50),
	MAINTOPIC VARCHAR(50),
	CONTRIBUTIONTYPE VARCHAR(50),
	ABSTRACT VARCHAR(500),
	PDFFILE VARCHAR(255),
	primary key (ID)
);

create or replace TABLE MATRIX.PUBLIC.AUTOR (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 order,
	NOM VARCHAR(50),
	PRENOM VARCHAR(50),
	INSTITUTION VARCHAR(100),
	COUNTRY VARCHAR(50),
	primary key (ID)
);

create or replace TABLE MATRIX.PUBLIC.ARTICLE_AUTOR_RELATION (
	ARTICLE_ID NUMBER(38,0),
	AUTOR_ID NUMBER(38,0),
	foreign key (ARTICLE_ID) references MATRIX.PUBLIC.ARTICLE_SCIENTIFIQUE(ID),
	foreign key (AUTOR_ID) references MATRIX.PUBLIC.AUTOR(ID)
);

create or replace TABLE MATRIX.PUBLIC.COORDONNEES (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 order,
	ID_USER NUMBER(38,0),
	EMAIL VARCHAR(100),
	PHONENUMBER VARCHAR(20),
	MOTDEPASSE VARCHAR(100),
	EMAIL_VERIFIED BOOLEAN DEFAULT FALSE,
	PHONE_VERIFIED BOOLEAN DEFAULT FALSE,
	VERIFICATION_TOKEN VARCHAR(100),
	primary key (ID)
);

create or replace TABLE MATRIX.PUBLIC.PAIEMENT (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 order,
	ID_USER NUMBER(38,0),
	CREDITNUMBER VARCHAR(20),
	EXPIRATIONDATE DATE,
	CVV VARCHAR(10),
	NAME_CARD VARCHAR(50),
	primary key (ID)
);

create or replace TABLE MATRIX.PUBLIC.TWO_FA_USER (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 order,
	USER_ID NUMBER(38,0) NOT NULL,
	ENABLE_2FA BOOLEAN DEFAULT FALSE,
	APP_AUTHENTICATION_ENABLED BOOLEAN DEFAULT FALSE,
	APP_AUTHENTICATION VARCHAR(100),
	PHONE_AUTHENTICATION_ENABLED BOOLEAN DEFAULT FALSE,
	PHONE_AUTHENTICATION VARCHAR(20),
	primary key (ID)
);

create or replace TABLE MATRIX.PUBLIC.USER_ARTICLE (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 order,
	IDUSER NUMBER(38,0),
	IDARTICLE NUMBER(38,0),
	STATUS VARCHAR(20),
	primary key (ID)
);

create or replace TABLE MATRIX.PUBLIC.USER_RECUP (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 order,
	USER_ID NUMBER(38,0) NOT NULL,
	EMAIL VARCHAR(100),
	PHONE_NUMBER VARCHAR(20),
	primary key (ID)
);

create or replace TABLE MATRIX.PUBLIC.UTILISATEUR (
	ID NUMBER(38,0) NOT NULL autoincrement start 1 increment 1 order,
	NOM VARCHAR(50),
	PRENOM VARCHAR(50),
	DATEDENAISANCE DATE,
	SEXE VARCHAR(10),
	primary key (ID)
);
